### ISSUE TITLE
Unlock some doors and enable the hanger elevator.

### ISSUE THREAD

**Issue by glasnonck** [LaneDibello/Kotor-Randomizer-2#4]
### Summary
There are a few locked doors that make their modules inescapable until certain plot points have occurred, or just make certain zones hard to reach. Unlocking these doors would provide enhanced usability for the randomizer. Here are the doors of interest for this enhancement:

- [x] Temple Summit Exit
- [x] Courtyard Ruins Door
- [x] Leviathan Hanger Elevator

**Comment by LaneDibello** [comment]
I hadn't realized that you had already made a commit to your fork unlocking these doors. I went ahead and made my own solution that uses the new GFF features, so we don't have to store any additional resources for these doors. 

Basically instead of me editing the doors outside of the program and replacing the entire door file, this just programmatically edits the UTD file.

**Comment by LaneDibello** [comment]
Works like a charm. The two doors, and the elevators on the command deck and prison block are handled programmatically. Due to the complexity of the problem, I opted to upload a modded fix into resources for the Hanger elevator. I found this solution to be both cleaner and more time efficient.
