### ISSUE TITLE
Do not randomize invisible placeable models.

### ISSUE THREAD

**Issue by glasnonck** [LaneDibello/Kotor-Randomizer-2#8]
Randomizing invisible placeable models creates instability issues during randomized gameplay. These objects should be ignored whenever model randomization is performed. The Field_Data values for objects that have been identified as invisible models are given below.

- 0 = Invisible
- 54 = Invisible
- 142 = Invisible_Barrier
- 219 = InvisibleCaloNord
- 167 = InvisibleEbonContainer

**Comment by LaneDibello** [comment]
I resolved this with a slightly more elegant solution. In that if any placeable by default is an object we consider "Broken", we don't randomize it. Not only does this fix the invisible placeable issue, but will likely help the continued stability of the option. This is because the models in the "broken" category are generally used for special cases, and their randomization is more likely to be unsafe.
